### ISSUE TITLE
xtce.xml does not validate against schema

### ISSUE THREAD

**Issue by merose** [yamcs/quickstart#1]
Two problems with src/main/yamcs/mdb/xtce.xml:

1. The namespace used for the XTCE spec does not match the `targetNamespace` in the schema, causing warnings in oXygen.
2. The `<BaseContainer>` elements are not in a legal place, according to the schema. They must occur after `<EntryList>`.

**Comment by fqqb** [comment]
Looks like the header was mixing xtce 1.1 with 1.2.
Thanks for the report and fix
