### ISSUE TITLE
a run application problem

### ISSUE THREAD

**Issue by S1eepyBear** [yamcs/quickstart#17]
hello,I use this command to run this application:"mvn yamcs:run", here is the console output，it shows success，but I can't visiting http://localhost:8090/，I don't konw why.
one more thing，do you have more Use document for the jsle application，I want to konw how to use it. 
thank you！
Exception in thread "main" 20:40:59.531 _global [1] stdout java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/x8/xmvwdv3n13bc7c1r_q21frnh0000gn/T/librocksdbjni17940906133265893243.jnilib
20:40:59.531 _global [1] stdout         at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
20:40:59.531 _global [1] stdout         at java.base/java.lang.Runtime.load0(Runtime.java:755)
20:40:59.531 _global [1] stdout         at java.base/java.lang.System.load(System.java:1953)
20:40:59.531 _global [1] stdout         at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
20:40:59.531 _global [1] stdout         at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
20:40:59.531 _global [1] stdout         at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
20:40:59.531 _global [1] stdout         at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
20:40:59.531 _global [1] stdout         at org.rocksdb.FlushOptions.<clinit>(FlushOptions.java:9)
20:40:59.531 _global [1] stdout         at org.yamcs.yarch.rocksdb.RDBFactory.<clinit>(RDBFactory.java:41)
20:40:59.531 _global [1] stdout         at org.yamcs.YamcsServer.prepareStart(YamcsServer.java:1153)
20:40:59.531 _global [1] stdout         at org.yamcs.YamcsServer.main(YamcsServer.java:953)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.599 s
[INFO] Finished at: 2023-03-28T20:40:59+08:00
[INFO] ------------------------------------------------------------------------

**Comment by fqqb** [comment]
is this on a mac? The latest architecture (arm64) is not currently supported.
Our next release (5.8.0) will include support for that.

**Comment by S1eepyBear** [comment]
Yes it is. Look forward to your update.
