### ISSUE TITLE
mvn site does not work

### ISSUE THREAD

**Issue by merose** [yamcs/quickstart#20]
The command `$ mvn package site` does not work in the current quickstart. Instead the build fails with a missing class from the Doxia Maven plugin (which is indirectly referenced by the latest maven-site-plugin). This appears not to be a problem with the project itself, but with the default (latest) version of the maven-site-plugin. Specifying a version of that and the reporting plugin that is not the latest seems to work.

For example, adding these two additional plugins just before the end of the `<build>` section fix the problem:

~~~
... lines of pom.xml omitted ...
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.7.1</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-project-info-reports-plugin</artifactId>
        <version>3.0.0</version>
      </plugin>
    </plugins>
  </build>
</project>
~~~

These versions were suggested in a stackoverflow answer. I don't know if more recent versions also work.

**Comment by fqqb** [comment]
Can you say what is your Maven version?
(doesn't immediately reproduce on mine)

**Comment by fqqb** [comment]
Nevermind, I see the error now, when i use the mvnw script

**Comment by fqqb** [comment]
Pushed a commit which sets the latest versions of both of these.
