### ISSUE TITLE
Ignore un-stage files under VSCODE .history folder

### ISSUE THREAD

**Issue by Apaisal** [yamcs/quickstart#34]
Update .gitignore for VSCODE .history folder following this patch https://github.com/yamcs/quickstart/commit/e4ac711cd53d4066001f0aac6e321bc7a5ca2852

**Comment by fqqb** [comment]
i've never heard of this folder. Is this pure vscode, or coming from an extension?

**Comment by Apaisal** [comment]
It's coming from a Local History extension, not pure VSCODE yet.
This extension is useful when we develop locally without committing per period, It's like local history in ECLIPSE.

**Comment by fqqb** [comment]
think for this one may better to use global gitignore
