### ISSUE TITLE
Update build to allow for a configurable playback data rate

### ISSUE THREAD

**Issue by unlikelyzero** [yamcs/quickstart#37]
For testing purposes it is sometimes useful to be able to control the rate at which the telemetry simulator produces telemetry. As such, it would be helpful if the desired playback rate could be supplied as an optional runtime argument.

**Comment by akhenry** [comment]
For testing purposes it is sometimes useful to be able to control the rate at which the telemetry simulator produces telemetry. As such, it would be helpful if the desired playback rate could be supplied as an optional runtime argument.
