### ISSUE TITLE
`make all` references python instead of python3

### ISSUE THREAD

**Issue by unlikelyzero** [yamcs/quickstart#9]
The `make all` command references `python` instead of `python3 which is a problem for macOS users who are not in control of their own destiny (aka NASA-IT-managed machines). 

I'm not familiar with make and therefore do not know how we should handle this. I believe python will remain aliased on macOS machines for some time.

**Comment by fqqb** [comment]
Closing as per PR close.
The simulator.py script should work with both Python 2 and Python 3, so I assume current situation is fine for a while longer.

**Comment by unlikelyzero** [comment]
@fqqb i'll need to provide an implementation with .PHONY and some aliasing. Can you re-open this issue?

**Comment by fqqb** [comment]
Sorry had misunderstood.
Thinking maybe the python should also run in a container? It would avoid relying on the host's python.

**Comment by unlikelyzero** [comment]
Closed with https://github.com/yamcs/quickstart/pull/13
